import Config

# Configure your database
config :star_chart, StarChart.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "star_chart_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  # Query timeout (milliseconds)
  timeout: 60_000,
  # Time to wait for connection from pool (milliseconds)
  pool_timeout: 60_000,
  # Ownership timeout for tests (milliseconds)
  ownership_timeout: 60_000

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :star_chart, StarChartWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "fp9tf3G+HSONc3Sv0X+KoCM2Nxvs/7uPdpSuUqJbZZJAaP4DKrgwCPSo7ZPH6zYR",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Disable open api cache in dev
config :open_api_spex, :cache_adapter, OpenApiSpex.Plug.NoneCache
# Enable dev routes for dashboard and mailbox
config :star_chart, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# For development, use the local adapter with the Swoosh mailbox preview
config :star_chart, StarChart.Mailer, adapter: Swoosh.Adapters.Local

# Configure Swoosh API client
config :swoosh, :api_client, false

# Swoosh mailbox preview in browser
config :swoosh, :preview_port, 4001
